
# This is a basic workflow to showcase the use of Reusable Workflows call

name: Reusable Workflow user 3

on:
  workflow_dispatch:
jobs:
  call-workflow-1-in-local-repo:
    uses:partnerShaikShafivullaphilips/angular_project/.github/reusable_workflow_second.yml

