
# This is a basic workflow to showcase the use of Reusable Workflows call

name: Reusable Workflow user 2

on:
  workflow_dispatch:
  jobs:
  call-workflow:
    uses: partnerShaikShafivullaphilips/angular_project/.github/workflows/reusable.yml
  call-workflow:
    uses:partnerShaikShafivullaphilips/angular_project/.github/workflows/reusable_workflow_second.yml
