
# This is a basic workflow to showcase the use of Reusable Workflows call

name: Reusable Workflow user 1

on:
  workflow_dispatch:

jobs:
  do-it:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Run a one-line script
        run: echo Hello, from min work flow!

  jobs:
  call-workflow:
    uses: partnerShaikShafivullaphilips/angular_project/.github/workflows/reusable.yml
    with:
      image_name: my-awesome-app
      tag: $GITHUB_RUN_NUMBER
    secrets:
      registry_username: ${{secrets.REGISTRY_USERNAME}}
      registry_password: ${{secrets.REGISTRY_PASSWORD}}
